### ISSUE TITLE
Internal consistency error

### ISSUE THREAD

**Issue by RobinClowers** [bitwalker/combine#17] opened 2016-06-23 01:45 UTC
On erlang 19, elixir 1.3, I get this error:

```
== Compilation error on file lib/combine/parsers/text.ex ==
** (CompileError) Elixir.Combine.Parsers.Text: function float_impl/1+43:
  Internal consistency check failed - please report this bug.
  Instruction: {call,4,{f,129}}
  Error:       {multiple_match_contexts,[{x,0},1]}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by aaronjensen** [comment] 2016-06-23 02:40
@josevalim is this an elixir or erlang bug?

**Comment by RobinClowers** [comment] 2016-06-23 02:41
From what I read it looks like an erlang bug...

**Comment by josevalim** [comment] 2016-06-23 08:04
@RobinClowers sounds like an Erlang bug. We would need to write a small Erlang module that reproduces it.

**Comment by risq** [comment] 2016-06-23 08:08
Hi, I got a similar error on erlang 19, elixir 1.2.6, if that helps you :

```
==> combine
Compiled lib/combine/parser_state.ex
Compiled lib/combine/helpers.ex
Compiled lib/combine.ex
Compiled lib/combine/parsers/binary.ex
Compiled lib/combine/parsers/base.ex

== Compilation error on file lib/combine/parsers/text.ex ==
** (FunctionClauseError) no function clause matching in :elixir_errors.handle_file_error/2
    (elixir) src/elixir_errors.erl:186: :elixir_errors.handle_file_error("Elixir.Combine.Parsers.Text", {:beam_validator, {{Combine.Parsers.Text, :float_impl, 1}, {{:call, 4, {:f, 112}}, 43, {:multiple_match_contexts, [{:x, 0}, 1]}}}})
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :combine, "mix compile" failed. You can recompile this dependency with "mix deps.compile combine", update it with "mix deps.update combine" or clean it with "mix deps.clean combine"
```

(combine 0.7 from [timex deps](https://github.com/bitwalker/timex/blob/master/mix.exs#L38))

**Comment by adamkittelson** [comment] 2016-06-23 20:57
Duplicating my comment from #18 since I think they're duplicate issues with the only difference being the formatting of the error depending on whether Elixir 1.2.x or Elixir 1.3.0 is used.

I cloned this and played around with it a bit.

On Elixir 1.3.0 and Erlang 19.0 I get

```
== Compilation error on file lib/combine/parsers/text.ex ==
** (CompileError) Elixir.Combine.Parsers.Text: function float_impl/1+43:
  Internal consistency check failed - please report this bug.
  Instruction: {call,4,{f,137}}
  Error:       {multiple_match_contexts,[{x,0},1]}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

but if I change the `#{line}` at https://github.com/bitwalker/combine/blob/f5d11693a9a71d785b185ea515797381a25c5223/lib/combine/parsers/text.ex#L574 to `#{state.line}` it compiles.

**Comment by josevalim** [comment] 2016-06-23 21:33
Thanks @adamkittelson! It is definitely a bug in the Erlang compiler. It would be awesome if someone could isolate a minimum Elixir code sample that reproduces it, so we can translate it to Erlang and report it to OTP. :)

**Comment by adamkittelson** [comment] 2016-06-23 21:39
No problem @josevalim It's probably worth noting in trying to isolate an example that in the very next float_impl clause `line` is being pulled from the ParserState struct and interpolated into a string in a map update in exactly the same way without causing any issues, so I'm guessing the fact that the one that is blowing up is happening within a macro is relevant.

**Comment by bitwalker** [comment] 2016-06-24 00:24
Definitely seems related to the usage within a macro, though I'm not clear on why that would fail when the same thing outside a macro works. My assumption is the macro generates the same code, but apparently not.

**Comment by ericentin** [comment] 2016-06-24 01:04
I've been playing around with this and the issue does not appear in OTP 19.0-rc1. Only in 19.0. Going to keep playing around with it and see if I can isolate it.

Trying rc2 now.

**Comment by ericentin** [comment] 2016-06-24 01:21
I believe I have narrowed down the issue to this commit: https://github.com/erlang/otp/commit/b6e4235b7ce8851fdd37ba7308d2e58d8b996fd6

**Comment by ericentin** [comment] 2016-06-24 01:55
Here's the abstract code for the version with `line`:

``` erlang
{bin_element,574,
 {'case',
  [{location,0},{generated,true}],
  {var,574,'_@2'},
  [{clause,
    [{location,0},{generated,true}],
    [{var,574,'_@16'}],
    [[{call,
       [{location,0},{generated,true}],
       {remote,
        [{location,0},{generated,true}],
        {atom,0,erlang},
        {atom,
         [{location,0},{generated,true}],
         is_binary}},
       [{var,574,'_@16'}]}]],
    [{var,574,'_@16'}]},
   {clause,
    [{location,0},{generated,true}],
    [{var,574,'_@17'}],
    [],
    [{call,574,
      {remote,574,
       {atom,0,'Elixir.String.Chars'},
       {atom,574,to_string}},
      [{var,574,'_@17'}]}]}]},
 default,
 [binary]},
```

and here's the code for the version with `state.line`:

``` elixir
{:bin_element, 574,
 {:case, [location: 0, generated: true],
  {:case, [generated: true, location: 0], {:var, 574, :_@1},
   [{:clause, [generated: true, location: 0],
     [{:map, 574,
       [{:map_field_exact, 574, {:atom, 574, :line},
         {:var, 574, :_@16}}]}], [], [{:var, 574, :_@16}]},
    {:clause, [generated: true, location: 0],
     [{:var, 574, :_@16}],
     [[{:call, [generated: true, location: 0],
        {:remote, [generated: true, location: 0],
         {:atom, [generated: true, location: 0], :erlang},
         {:atom, [generated: true, location: 0], :is_map}},
        [{:var, 574, :_@16}]}]],
     [{:call, 574,
       {:remote, 574, {:atom, 574, :erlang},
        {:atom, 574, :error}},
       [{:tuple, 574,
         [{:atom, 574, :badkey}, {:atom, 574, :line},
          {:var, 574, :_@16}]}]}]},
    {:clause, [generated: true, location: 0],
     [{:var, 574, :_@16}], [],
     [{:call, [generated: true, location: 0],
       {:remote, [generated: true, location: 0],
        {:var, 574, :_@16}, {:atom, 574, :line}}, []}]}]},
  [{:clause, [location: 0, generated: true],
    [{:var, 574, :_@17}],
    [[{:call, [location: 0, generated: true],
       {:remote, [location: 0, generated: true],
        {:atom, 0, :erlang},
        {:atom, [location: 0, generated: true], :is_binary}},
       [{:var, 574, :_@17}]}]], [{:var, 574, :_@17}]},
   {:clause, [location: 0, generated: true],
    [{:var, 574, :_@18}], [],
    [{:call, 574,
      {:remote, 574, {:atom, 0, String.Chars},
       {:atom, 574, :to_string}}, [{:var, 574, :_@18}]}]}]},
 :default, [:binary]},
```

I'm going to keep looking at stuff but will be going to bed soon, so hope this helps someone continue the investigation into exactly what's happening...

**Comment by mneudert** [comment] 2016-07-20 18:56
Hey there,

I also got [aware](https://github.com/mneudert/geolix/issues/14) of this bug and was able to narrow it down to a minimal Elixir module triggering this error:

Repo: https://github.com/mneudert/elixir-erlang-consistency-failure
File: [consistency_failure.ex](https://github.com/mneudert/elixir-erlang-consistency-failure/blob/master/lib/consistency_failure.ex)
Travis: https://travis-ci.org/mneudert/elixir-erlang-consistency-failure/builds/146174257

(Builds for Erlang 19.0 have the error in the log, not reflected by the build state)

Then "fun" part are the various fixes I found for that error. I have created different modules for each solution working around the compiler issue.

Besides the (in my case) nice solution of just removing a case clause I could also prevent the error from happening by reassigning a variable. Replacing a `_` match with a name and then sending it to `IO.puts/1` also helped (variable name only had no effect). A different solution was to change the function called inside the case to not use binary pattern matching.

It looks like some problem with variables in combination with binary pattern matching. But that is pure guesswork on my side.

Hope it helps to narrow down the issue and/or create a pure Erlang module with that error.

**Comment by ericentin** [comment] 2016-07-20 19:26
This is very useful because now we can try translating this into Erlang to
see if the bug shows up there. Awesome!

**Comment by bitwalker** [comment] 2016-07-21 02:57
@mneudert Nice work! The minimal case required to trigger it is a lot simpler than I would've guessed, it should definitely be trivial to port that to Erlang and see if it happens there as well. I'll try and do that in the next day or so.

**Comment by plck1** [comment] 2016-09-08 05:10
+1

**Comment by amaranthrose** [comment] 2016-09-08 13:45
:+1:

**Comment by josevalim** [comment] 2016-09-27 11:49
Did anyone report this to the OTP team? If not, I will check if it was
fixed in OTP master and file a report otherwise.

## 

_José Valimwww.plataformatec.com.br
http://www.plataformatec.com.br/Founder and Director of R&D_

**Comment by ericentin** [comment] 2016-09-27 14:20
@josevalim I don't think so. I had wanted to, but never managed to create an erlang test case.

**Comment by josevalim** [comment] 2016-09-27 15:47
Bug reported: https://bugs.erlang.org/browse/ERL-268

I also found a bug on the Elixir compiler, so jackpot. :D

**Comment by bitwalker** [comment] 2016-09-27 16:02
Nice :), thanks José!

**Closed as completed** 2016-11-07 17:10 UTC
