### ISSUE TITLE
Erlang 19 Compilation Error

### ISSUE THREAD

**Issue by veverkap** [bitwalker/combine#18] opened 2016-06-23 14:47 UTC
I'm getting a compilation error with a project that uses combine.

Elixir 1.2.6
Erlang 19

```
== Compilation error on file lib/combine/parsers/text.ex ==
** (FunctionClauseError) no function clause matching in :elixir_errors.handle_file_error/2
    (elixir) src/elixir_errors.erl:186: :elixir_errors.handle_file_error("Elixir.Combine.Parsers.Text", {:beam_validator, {{Combine.Parsers.Text, :float_impl, 1}, {{:call, 4, {:f, 50}}, 43, {:multiple_match_contexts, [{:x, 0}, 1]}}}})
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :combine, "mix compile" failed. You can recompile this dependency with "mix deps.compile combine", update it with "mix deps.update combine" or clean it with "mix deps.clean combine"
```

**Comment by veverkap** [comment] 2016-06-23 14:50
Doing it outside the project kills things too :(

```
threatsim@trophoblastprecantation-i-557634c9:/srv/workers$ git clone git@github.com:bitwalker/combine.git
Cloning into 'combine'...
remote: Counting objects: 520, done.
remote: Total 520 (delta 0), reused 0 (delta 0), pack-reused 520
Receiving objects: 100% (520/520), 189.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (257/257), done.
Checking connectivity... done.
threatsim@trophoblastprecantation-i-557634c9:/srv/workers$ cd combine/
threatsim@trophoblastprecantation-i-557634c9:/srv/workers/combine$ mix deps.get
Running dependency resolution
* Getting ex_doc (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ex_doc-0.11.5.tar)
  Fetched package
* Getting earmark (Hex package)
  Checking package (https://repo.hex.pm/tarballs/earmark-0.2.1.tar)
  Fetched package
* Getting benchfella (Hex package)
  Checking package (https://repo.hex.pm/tarballs/benchfella-0.3.2.tar)
  Fetched package
* Getting dialyze (Hex package)
  Checking package (https://repo.hex.pm/tarballs/dialyze-0.2.1.tar)
  Fetched package
threatsim@trophoblastprecantation-i-557634c9:/srv/workers/combine$ mix test
Compiled lib/combine/parser_state.ex
Compiled lib/combine.ex
Compiled lib/combine/helpers.ex
Compiled lib/combine/parsers/binary.ex
Compiled lib/combine/parsers/base.ex

== Compilation error on file lib/combine/parsers/text.ex ==
** (FunctionClauseError) no function clause matching in :elixir_errors.handle_file_error/2
    (elixir) src/elixir_errors.erl:186: :elixir_errors.handle_file_error("Elixir.Combine.Parsers.Text", {:beam_validator, {{Combine.Parsers.Text, :float_impl, 1}, {{:call, 4, {:f, 388}}, 43, {:multiple_match_contexts, [{:x, 0}, 1]}}}})
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

threatsim@trophoblastprecantation-i-557634c9:/srv/workers/combine$
```

**Comment by adamkittelson** [comment] 2016-06-23 20:14
I cloned this and played around with it a bit.

On Elixir 1.3.0 and Erlang 19.0 I get

```
== Compilation error on file lib/combine/parsers/text.ex ==
** (CompileError) Elixir.Combine.Parsers.Text: function float_impl/1+43:
  Internal consistency check failed - please report this bug.
  Instruction: {call,4,{f,137}}
  Error:       {multiple_match_contexts,[{x,0},1]}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

but if I change the `#{line}` at https://github.com/bitwalker/combine/blob/f5d11693a9a71d785b185ea515797381a25c5223/lib/combine/parsers/text.ex#L574 to `#{state.line}` it compiles.

**Comment by bitwalker** [comment] 2016-06-24 00:19
Damn, this is an interesting one. @adamkittelson can you make a PR with your fix so I can merge it and release a fix? I'll get it done tonight one way or the other.

**Comment by bitwalker** [comment] 2016-06-24 03:24
Closing this as a duplicate of #17 for now

**Closed as completed by bitwalker** 2016-06-24 03:24 UTC
