### ISSUE TITLE
Elixir.Combine.Parsers.Text: function float_impl/1+43:

### ISSUE THREAD

**Issue by sashaafm** [bitwalker/combine#23] opened 2016-09-02 14:58 UTC
```
== Compilation error on file lib/combine/parsers/text.ex ==
** (CompileError) Elixir.Combine.Parsers.Text: function float_impl/1+43:
  Internal consistency check failed - please report this bug.
  Instruction: {call,4,{f,129}}
  Error:       {multiple_match_contexts,[{x,0},1]}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

I'm getting this error which I believe is due to Erlang 19 breaking something. I'm actually having quite a few problems with OTP 19.

I've got no idea on what information to give. I'm on Ubuntu 16.04 64-bit. Elixir version is 1.3

**Comment by bitwalker** [comment] 2016-11-07 16:57
I can't reproduce this, could you give it another shot (make sure you're on the latest version of combine too)?

**Comment by bitwalker** [comment] 2016-11-07 17:11
I can confirm that this issue was fixed in a 19.x release (the initial OTP 19 release did have a bug, but a PR was merged to resolve that here).

**Closed as completed by bitwalker** 2016-11-07 17:11 UTC
Labels: cannot reproduce
